version: '3.5'

networks:
  test:
    name: fastapi_example

services:
  mysql_db:
    image: mysql:8.0.31
    container_name: jurassicpark-db
    ports:
      - 3306:3306
    networks:
      - test
    environment:
      - MYSQL_ROOT_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - test

  fastapi:
    image: fast-api-example:latest
    container_name: fastapi
    restart: always
    ports: 
      - 8000:8000
    networks:
      - test
    volumes:
      - ./jurassicpark:/code/app
    environment:
      - MYSQL_URL=mysql://root:example@jurassicpark-db:3306/JurassicPark
    depends_on:
      - mysql_db